# bg_en_ic.py
import re
from .utils import apply_replacements, apply_regex_replacements

regex_patterns = (
    (re.compile(r"Ж[Жж]"), "Ж"),
    (re.compile(r"ж[Жж]"), "ж"),
    (re.compile(r"Ц[Цц]"), "Ц"),
    (re.compile(r"ц[Цц]"), "ц"),
    (re.compile(r"Ч[Чч]"), "Ч"),
    (re.compile(r"ч[Чч]"), "ч"),
    (re.compile(r"Ш[Шш]"), "Ш"),
    (re.compile(r"ш[Шш]"), "ш"),
    (re.compile(r"Щ[Щщ]"), "Щ"),
    (re.compile(r"щ[Щщ]"), "щ"),
    (re.compile(r"И[Яя](\b|$)"), "IA"),
    (re.compile(r"и[Яя](\b|$)"), "ia"),
)

char_map = {
    "А": "A",
    "а": "a",
    "Б": "B",
    "б": "b",
    "В": "V",
    "в": "v",
    "Г": "G",
    "г": "g",
    "Д": "D",
    "д": "d",
    "Е": "E",
    "е": "e",
    "Ж": "Zh",
    "ж": "zh",
    "З": "Z",
    "з": "z",
    "И": "I",
    "и": "i",
    "Й": "Y",
    "й": "y",
    "К": "K",
    "к": "k",
    "Л": "L",
    "л": "l",
    "М": "M",
    "м": "m",
    "Н": "N",
    "н": "n",
    "О": "O",
    "о": "o",
    "П": "P",
    "п": "p",
    "Р": "R",
    "р": "r",
    "С": "S",
    "с": "s",
    "Т": "T",
    "т": "t",
    "У": "U",
    "у": "u",
    "Ф": "F",
    "ф": "f",
    "Х": "H",
    "х": "h",
    "Ц": "Ts",
    "ц": "ts",
    "Ч": "Ch",
    "ч": "ch",
    "Ш": "Sh",
    "ш": "sh",
    "Щ": "Sht",
    "щ": "sht",
    "Ъ": "A",
    "ъ": "a",
    "Ь": "Y",
    "ь": "y",
    "Ю": "Yu",
    "ю": "yu",
    "Я": "Ya",
    "я": "ya",
}

def transliterate(src_text: str) -> str:
    """Return transliterated string"""
    src_text = apply_regex_replacements(src_text, regex_patterns)
    src_text = apply_replacements(src_text, char_map)
    return src_text
