# mn_cyr_en_mns.py
# Transliteration of Mongolian per the Mongolian National Standard
from .utils import apply_replacements

char_map = {
    "А": "A",
    "Б": "B",
    "В": "V",
    "Г": "G",
    "Д": "D",
    "Е": "Ye",
    "Ё": "Yo",
    "Ж": "J",
    "З": "Z",
    "К": "K",
    "И": "I",
    "Й": "I",
    "Л": "L",
    "М": "M",
    "Н": "N",
    "О": "O",
    "Ө": "Ö",
    "П": "P",
    "Р": "R",
    "С": "S",
    "Т": "T",
    "У": "U",
    "Ү": "Ü",
    "Ф": "F",
    "Х": "Kh",
    "Ц": "Ts",
    "Ч": "Ch",
    "Ш": "Sh",
    "Щ": "Sh",
    "Ъ": "I",
    "Ы": "Y",
    "Ь": "I",
    "Э": "E",
    "Ю": "Yu",
    "Я": "Ya",
    "а": "a",
    "б": "b",
    "в": "v",
    "г": "g",
    "д": "d",
    "е": "ye",
    "ё": "yo",
    "ж": "j",
    "з": "z",
    "к": "k",
    "и": "i",
    "й": "i",
    "л": "l",
    "м": "m",
    "н": "n",
    "о": "o",
    "ө": "ö",
    "п": "p",
    "р": "r",
    "с": "s",
    "т": "t",
    "у": "u",
    "ү": "ü",
    "ф": "f",
    "х": "kh",
    "ц": "ts",
    "ч": "ch",
    "ш": "sh",
    "щ": "sh",
    "ъ": "i",
    "ы": "y",
    "ь": "i",
    "э": "e",
    "ю": "yu",
    "я": "ya",
    # "Є": "Ö",
    # "Ѳ": "Ö",
    # "V": "Ü",
    # "Ї": "Ü",
    # "є": "ö",
    # "ѳ": "ö",
    # "v": "ü",
    # "ї": "ü",
}

def transliterate(src_text: str) -> str:
    """Return transliterated string"""
    src_text = apply_replacements(src_text, char_map)
    return src_text

