# ru_cyr_en_ala_lc.py
from .utils import apply_replacements

# The American Library Association and Library of Congress 
# Romanization Tables for Russian, or the Library of Congress system
char_map = {
    'а': 'a',
    'б': 'b',
    'в': 'v',
    'г': 'g',
    'д': 'd',
    'е': 'e',
    'ё': 'ë',
    'ж': 'zh',
    'з': 'z',
    'и': 'i',
    'й': 'ĭ',
    'к': 'k',
    'л': 'l',
    'м': 'm',
    'н': 'n',
    'о': 'o',
    'п': 'p',
    'р': 'r',
    'с': 's',
    'т': 't',
    'у': 'u',
    'ф': 'f',
    'х': 'kh',
    'ц': 't͡s',
    'ч': 'ch',
    'ш': 'sh',
    'щ': 'shch',
    'ъ': '″',
    'ы': 'y',
    'ь': '′',
    'э': 'ė',
    'ю': 'i͡u',
    'я': 'i͡a',
    'А': 'A',
    'Б': 'B',
    'В': 'V',
    'Г': 'G',
    'Д': 'D',
    'Е': 'E',
    'Ё': 'Ë',
    'Ж': 'Zh',
    'З': 'Z',
    'И': 'I',
    'Й': 'Ĭ',
    'К': 'K',
    'Л': 'L',
    'М': 'M',
    'Н': 'N',
    'О': 'O',
    'П': 'P',
    'Р': 'R',
    'С': 'S',
    'Т': 'T',
    'У': 'U',
    'Ф': 'F',
    'Х': 'Kh',
    'Ц': 'T͡S',
    'Ч': 'Ch',
    'Ш': 'Sh',
    'Щ': 'Shch',
    'Ъ': '″',
    'Ы': 'Y',
    'Ь': '′',
    'Э': 'Ė',
    'Ю': 'I͡U',
    'Я': 'I͡A',
}

def transliterate(src_text: str) -> str:
    """Return transliterated string"""
    src_text = apply_replacements(src_text, char_map)
    return src_text