# sr_cyr_en_ic.py
from .utils import apply_replacements

char_map = {
    "А": "A",
    "а": "a",
    "Б": "B",
    "б": "b",
    "В": "V",
    "в": "v",
    "Г": "G",
    "г": "g",
    "Д": "D",
    "д": "d",
    "Ђ": "Dj",
    "ђ": "dj",
    "Е": "E",
    "е": "e",
    "Ж": "Z",
    "ж": "z",
    "З": "Z",
    "з": "z",
    "И": "I",
    "и": "i",
    "Ј": "J",
    "ј": "j",
    "К": "K",
    "к": "k",
    "Л": "L",
    "л": "l",
    "Љ": "Lj",
    "љ": "lj",
    "М": "M",
    "м": "m",
    "Н": "N",
    "н": "n",
    "Њ": "Nj",
    "њ": "nj",
    "О": "O",
    "о": "o",
    "П": "P",
    "п": "p",
    "Р": "R",
    "р": "r",
    "С": "S",
    "с": "s",
    "Т": "T",
    "т": "t",
    "Ћ": "C",
    "ћ": "c",
    "У": "U",
    "у": "u",
    "Ф": "F",
    "ф": "f",
    "Х": "H",
    "х": "h",
    "Ц": "C",
    "ц": "c",
    "Ч": "C",
    "ч": "c",
    "Џ": "Dz",
    "џ": "dz",
    "Ш": "S",
    "ш": "s",
    "’": "",
    "'": "",
}

def transliterate(src_text: str) -> str:
    """Return transliterated string"""
    src_text = apply_replacements(src_text, char_map)
    return src_text
